name: Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: swift:6.2.0-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: swift build
